#!/bin/bash
echo "\n           __                                "
echo "    ____  / /___ ___  ______  ___  _________ "
echo "   / __ \/ / __ \`/ / / /_  / / _ \\/ ___/ __ \\"
echo "  / /_/ / / /_/ / /_/ / / /_/  __/ /  / /_/ /"
echo " / .___/_/\\__,_/\\__, / /___/\\___/_/   \\____/ "
echo "/_/            /____/                        \n"
echo "---------------------------------------------\n"
echo " Version "
echo "---------------------------------------------\n"
echo "  https://zero.io"
echo "  https://github.com/playzero"
echo "---------------------------------------------\n"
echo "  Docs:    docs.zero.io"
echo "  Bugs:    github.com/playzero/playzero/issues"
echo "  Forums:  forum.zero.io"
echo "  Chat:    gitter.im/playzero/playzero"
echo "\n"
